In [1]:
import numpy as np 

In [9]:
first_np_array = np.array([10,10,10])
first_np_array * 10

array([100, 100, 100])

In [13]:
second_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
my_list = []

for number in range(1,11):
    my_list.append(number)

my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [21]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
my_sports = np.array(['Padel', 'Boxeo', 'Running'])

In [24]:
my_sports[0]

np.str_('Padel')

In [25]:
my_sports[-1]

np.str_('Running')

In [29]:
print(type(my_sports[0]))
print(type(my_sports))

<class 'numpy.str_'>
<class 'numpy.ndarray'>


In [32]:
my_sequence = np.arange(10,-0.5,-0.5)
my_sequence

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ])

In [35]:
my_rand_matrix = np.random.randint(10,21, size=(5,2))
my_rand_matrix

array([[11, 18],
       [15, 11],
       [16, 17],
       [11, 15],
       [15, 20]], dtype=int32)

In [41]:
print(my_rand_matrix.ndim)
print(my_rand_matrix.shape)
print(my_rand_matrix.size)
print(my_rand_matrix.itemsize)
print(my_rand_matrix.nbytes)

2
(5, 2)
10
4
40


In [42]:
array_1 = np.array([1,2,3,4,5])
array_2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_3 = np.array([[[1,10], [2, 20], [3, 30]],
                    [[4, 40], [5, 50], [6, 60]],
                    [[7, 70], [8, 80], [9, 90]]])

print(array_1.ndim)
print(array_2.ndim)
print(array_3.ndim)

1
2
3


In [60]:
x = np.arange(10)

In [82]:
print(x[::2])
print(x[1::2])
print(x[::-1])
print(x[:-3:-1])
print(x[-3::-1])

[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[9 8]
[7 6 5 4 3 2 1 0]


In [83]:
array_multi = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

In [102]:
print(array_multi)
print('\n')
print(array_multi[:2,:3])
print('\n')
print(array_multi[:,::2])
print('\n')
print(array_multi[::-1])
print('\n')
print(array_multi[::,::-1])
print('\n')
print(array_multi[::-1,::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


[[1 2 3]
 [6 7 8]]


[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]


[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [114]:
x = np.array([2,4,5,2,3,7,2,2])

print(x)
print(x >= 5)

[2 4 5 2 3 7 2 2]
[False False  True False False  True False False]


In [115]:
x[x >= 5]


array([5, 7])

In [124]:
x = x.reshape((2,4))

In [130]:
y = np.arange(30).reshape((6,5))

In [131]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [133]:
x = np.arange(10) + np.arange(10)
y = np.arange(10) + np.arange(10)

In [134]:
np.concatenate((x,y))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18])

In [135]:
xy = np.array([[1,2,3],
              [4,5,6]])

In [139]:
np.concatenate([xy,xy], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [143]:
np.vstack([xy,xy])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [144]:
np.hstack([xy,xy])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [145]:
xy = np.array([[1,2,3],
              [4,5,6]])


print(np.where(xy < 4, 10, 20))
print(np.where(xy < 4, 10, xy))

[[10 10 10]
 [20 20 20]]
[[10 10 10]
 [ 4  5  6]]


In [150]:
xy = np.array([[1,2,3],
              [4,5,6]])

print(np.where(xy < 4, 10, 20))
print(np.where(xy < 4, 10, xy))

[[10 10 10]
 [20 20 20]]
[[10 10 10]
 [ 4  5  6]]


In [151]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
print(x)
x1,x2 = np.split(x, 2)
print(x1)
print(x2)
x1, x2, x3 = np.split(x, [2, 5])
print(x1)
print(x2)
print(x3)


[ 1  2  3 99 99  3  2  1]
[ 1  2  3 99]
[99  3  2  1]
[1 2]
[ 3 99 99]
[3 2 1]


In [152]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

77.6 ms ± 1.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
385 μs ± 6.21 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [154]:
np.min(big_array), np.max(big_array)

(np.float64(4.3369991631347915e-07), np.float64(0.9999994195855284))

In [155]:
big_array.sum()

np.float64(499813.92739070544)

In [160]:
M = np.random.random((3, 4))
print(M)

[[0.64822027 0.77583412 0.13227064 0.27592926]
 [0.63238114 0.3103903  0.08301709 0.66258886]
 [0.91030249 0.44813362 0.17746095 0.8054109 ]]


In [164]:
M.sum(axis=1)

array([1.8322543 , 1.6883774 , 2.34130795])